# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PWA Stats
email: info@cloudfour.com
description: A collection of Progressive Web App case studies.
repository: cloudfour/pwastats
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.pwastats.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cloudfour
github_username: cloudfour
author: PWA Community
timezone: America/Los_Angeles
permalink: /:year/:month/:title/

github:
  repository_url: https://github.com/cloudfour/pwastats
  issues_url: https://github.com/cloudfour/pwastats/issues/new

paginate: 12

collections:
  tags:
    output: true
    permalink: /tags/:title

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
      layout: permalink
  -
    scope:
      path: ""
      type: tags
    values:
      layout: tag

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - LICENSE
  - README.md
  - node_modules
  - scripts
  - sw.js
  - workbox-config.js
